external_sources: []
exclude:
  - assets/jupyter/blog.ipynb
plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-link-attributes
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
imagemagick:
  enabled: false
